[package]
name = "extension"
version = "0.1.0"
edition.workspace = true
rust-version.workspace = true
[dependencies]
lambda-extension = "0.11.0"
serde = "1"
tokio = { version = "1", features = ["macros"] }
